import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { name, email, message } = await request.json();

    if (!name || !email || !message) {
      return NextResponse.json(
        { error: "Name, email, and message are required fields." },
        { status: 400 }
      );
    }

    const emailAddress = process.env.EMAIL_ADDRESS || "tirth.p.patel143@gmail.com";
    const gmailPasskey = process.env.GMAIL_PASSKEY;

    if (!gmailPasskey) {
      console.warn("GMAIL_PASSKEY is not defined in environment variables. Email will not be sent.");
      return NextResponse.json(
        { error: "Email backend is not configured yet. Please configure GMAIL_PASSKEY in your environment." },
        { status: 500 }
      );
    }

    // Set up Gmail Nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: emailAddress,
        pass: gmailPasskey,
      },
    });

    const mailOptions = {
      from: emailAddress,
      to: emailAddress, // Send the message to yourself!
      replyTo: email,   // Let yourself reply directly to the sender's email
      subject: `💼 Portfolio Contact Form: ${name}`,
      text: `You received a new message from your portfolio contact form:\n\nName: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px; background-color: #fafafa;">
          <h2 style="color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; margin-top: 0;">New Portfolio Message</h2>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
              <td style="padding: 10px 0; font-weight: bold; width: 30%; color: #555555;">Name:</td>
              <td style="padding: 10px 0; color: #111111;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; width: 30%; color: #555555;">Email:</td>
              <td style="padding: 10px 0;"><a href="mailto:${email}" style="color: #3b82f6; text-decoration: none;">${email}</a></td>
            </tr>
          </table>
          
          <div style="background-color: #ffffff; padding: 15px; border-left: 4px solid #3b82f6; border-radius: 4px; margin-top: 10px;">
            <p style="margin-top: 0; font-weight: bold; color: #555555;">Message:</p>
            <p style="margin-bottom: 0; line-height: 1.6; color: #333333; white-space: pre-wrap;">${message}</p>
          </div>
          
          <div style="margin-top: 30px; font-size: 0.8rem; color: #777777; text-align: center; border-top: 1px solid #e0e0e0; padding-top: 15px;">
            This email was automatically generated by your Next.js portfolio website.
          </div>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Nodemailer error:", error);
    return NextResponse.json(
      { error: error?.message || "Failed to transmit message." },
      { status: 500 }
    );
  }
}
